apiVersion: batch/v1
kind: Job
metadata:
  name: qualifier
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
      - name: qualifier
        image: asserts/qualifier:v0.1.0
        command:
          - python
          - cli.py
          - --host
          - http://prometheus-server.default.svc.cluster.local:9090
      restartPolicy: Never
  backoffLimit: 1
